### PR TITLE
Refactor cue sheet implementation

### PR DESCRIPTION
**Pull request by Nadahar**
This replaces the `Cuelib` dependency and refactors most of the code related to cue sheet handling.

---
This change is [Reviewable](https://reviewable.io/reviews/digitalmediaserver/digitalmediaserver/69)

### CODE REVIEW

**Comment by Nadahar** [comment]
A windows build can be found here: http://superbum.org/downloads/DMS-setup-ReplaceCuelib.exe

**Comment by Sami32** [comment]
Can i test it with the JAR only?
Because i don't think that your build is XP compatible ;)

**Comment by Nadahar** [comment]
No, JAR only won't work. What isn't XP compatible? The FFmpeg version? Isn't it easier to just replace it or select the executable you want in the engines configuration?

**Comment by Sami32** [comment]
Ok. Not straith forward. Thanks for the build ;)

**Comment by Nadahar** [comment]
I've fixed the FLAC parsing issue:   http://superbum.org/downloads/dms-ReplaceCuelib.jar

**Comment by Nadahar** [comment]
@Sami32 I still don't fully understand the problem. If the problem is still there and you have the database enabled, please try without it. If that doesn't help, please tell me exactly which file so I can see what happens with it in the log.

**Comment by Sami32** [comment]
The JAudiotagger bug is fixed, but it still doesn't work on teal TV.
Did you tried on your TV?
Glenn-Miller---Music-of-Your-Life--Best-of-Glenn-Miller.flac (149 MB)

**Comment by Nadahar** [comment]
@Sami32 I think I've fixed the bug. I'd be very happy if you'd test the latest version: http://superbum.org/downloads/dms-ReplaceCuelib.jar (finished uploading in 8 minutes)

**Comment by Sami32** [comment]
Yes, i can confirm that :+1:

**Pull request merged**
