### PR TITLE
MIME types little refactoring draft

### PR DESCRIPTION
**Pull request by Sami32**
Work in progress

---
This change is [Reviewable](https://reviewable.io/reviews/digitalmediaserver/digitalmediaserver/23)

### CODE REVIEW

**Comment by Nadahar** [comment]
@Sami32 Great, but you're not working with the latest version. Mime types are no longer found in ```HTTPResource``` for example (those are moved to ```KnownMimeTypes```).

**Comment by Sami32** [comment]
Sorry, i don't know how i managed to do that :(

**Comment by Nadahar** [comment]
@Sami32 Don't close it, you will ruin the PR.

Just update/rebase the branch and continue...

**Comment by Nadahar** [comment]
I see it as unlikely that this will be continued now, so I'm closing it. A lot of things have changed since this was created.

**Comment by Nadahar** [comment]
New plan, resurrection attempt..

**Comment by Sami32** [comment]
It is there now:
https://github.com/Sami32/DigitalMediaServer/tree/MIMETypesBis

**Pull request closed without merging**
