### PR TITLE
Separate the two DSD formats

### PR DESCRIPTION
**Pull request by Sami32**
This change is [Reviewable](https://reviewable.io/reviews/digitalmediaserver/digitalmediaserver/8)

### CODE REVIEW

**Comment by Nadahar** [comment]
I think we've discussed this before, remind me what the purpose of separating between them is as I don't remember.

---

Reviewed 8 of 12 files at r1.
Review status: 7 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/net/pms/formats/audio/DSF.java, line 26 at r1](https://reviewable.io:443/reviews/digitalmediaserver/digitalmediaserver/8#-Kq_1RCIrNdToOembgST:-Kq_1RCIrNdToOembgSU:b-77h28b) ([raw file](https://github.com/digitalmediaserver/digitalmediaserver/blob/9e4b000ee61b41a3690dab5ffaf61a1a5b08af9b/src/main/java/net/pms/formats/audio/DSF.java#L26)):*
> ```Java
> 		 * {@inheritDoc}
> 		 */
> 		@Override
> ```

I'm trying to clean away all those ```{@inheritDoc}``` comments as they serve no purpose. When a method is overridden, it will automatically inherit the JavaDoc of the super method unless the JavaDoc is specified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/digitalmediaserver/digitalmediaserver/8#-:-Kq_-kju-Y8pmCRzWoJ8:b-8azndx)*

**Comment by Sami32** [comment]
By @ler0y [request](https://github.com/UniversalMediaServer/UniversalMediaServer/issues/623).

**Comment by Sami32** [comment]
*[a discussion](https://reviewable.io:443/reviews/digitalmediaserver/digitalmediaserver/8#-Kq_8kDa96cAiZcfEC04:-Kq_8kDd1mb5KR_7RBcq:b-896fix) (no related file):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/digitalmediaserver/digitalmediaserver/8)*

**Comment by Sami32** [comment]
*[src/main/java/net/pms/formats/audio/DSF.java, line 26 at r1](https://reviewable.io:443/reviews/digitalmediaserver/digitalmediaserver/8#-Kq_1RCIrNdToOembgST:-Kq_92Ttg4j91cm1pBUN:b-896fix) ([raw file](https://github.com/digitalmediaserver/digitalmediaserver/blob/9e4b000ee61b41a3690dab5ffaf61a1a5b08af9b/src/main/java/net/pms/formats/audio/DSF.java#L26)):*
<details><summary><i>Previously, Nadahar (Nadar) wrote…</i></summary><blockquote>

I'm trying to clean away all those ```{@inheritDoc}``` comments as they serve no purpose. When a method is overridden, it will automatically inherit the JavaDoc of the super method unless the JavaDoc is specified.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/digitalmediaserver/digitalmediaserver/8)*

**Comment by Nadahar** [comment]
Reviewed 3 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/digitalmediaserver/digitalmediaserver/8)*

**Comment by Sami32** [comment]
:smile:

**Comment by Nadahar** [comment]
Hrmf, you merged not rebased this one. Had to rebase master...

**Comment by Nadahar** [comment]
@Sami32 I hope my comment didn't bother you. I only wanted to say that it ended up with a merge commit, which isn't ideal as I'm sure you agree with. I've fixed it though.

**Comment by Sami32** [comment]
No, don't worry, i was just busy to other stuff.

Sorry, i didn't saw it, it was too late before sleep.
That's said, i know why i asked you to make it by default :wink: 
But if you said that it will remember my last setting, it should be fine the next time.

**Comment by Nadahar** [comment]
@Sami32 
> But if you said that it will remember my last setting, it should be fine the next time.

No it won't, your "last time" was "merge" 😛

**Comment by Sami32** [comment]
It was also my first time here, so if it remember setting as you suggested it will need an other PR approval :stuck_out_tongue: , as it seem that it is by repository remembering.

**Comment by Nadahar** [comment]
@Sami32 Exactly, but if you think it's already ok, we will have the same problem the next time. I think the best thing is to be careful when merging, and make sure everything is as it should. I like the merging in Reviewable as you'll have to *hold* the button until "armed" to make sure you really intend to.

**Comment by Sami32** [comment]
Do it take care of white trailing spaces as well :tongue:

**Comment by Nadahar** [comment]
@Sami32 I don't know where you see the white space errors, but please inform me when you do. I'm not aware of that I am commiting those, or even how it's possible given that both Eclipse and Git prevents me from doing it.

**Comment by Sami32** [comment]
I already told. Check at the recent commit 9441144.
```
src/test/java/net/pms/configuration/RendererConfigurationTest.java:44: trailing whitespace.
src/test/java/net/pms/dlna/LibMediaInfoParserTest.java:33: trailing whitespace.
```

**Comment by Nadahar** [comment]
@Sami32 That is extremely annoying and I don't understand it. I did that in Eclipse, so Eclipse should have removed them. I suspect that I added these during a rebase though, so the Git check might not have applied, but still. Very strange.

**Comment by Sami32** [comment]
That's not the end of the world, but it's surprise me, because in UMS it doesn't happen to since long, and now in DMS near all.

Perhaps you should add an trailing white spaces rebasing Git alias, as i do ?
That's said, me i've issue in committing in PR, because i didn't want to implement the "white commit" as you did.

I also don't understand how it happen to you, but when you insisted a little to much for my "careless" merge i just wanted "return the ball" :stuck_out_tongue_winking_eye:

**Comment by Nadahar** [comment]
@Sami32 Not sure what you mean about "rebasing Git alias", but I could add a similar hook for rebasing as I have for committing. The problem is that rebases can be complicated as they are, and for big ones with a lot of code I didn't write, it could be quite hopeless.

If I could only make sure that any code I commit myself is "clean", it would be sufficiant for me, but it clearly isn't working like it should now. I'll have to do some testing and try to figure it out.

**Comment by Sami32** [comment]
`rebase --whitespace=fix`

**Comment by Nadahar** [comment]
Ok, I'd never want git to *edit* the code, I want to be warned and fix it myself.

**Comment by Sami32** [comment]
Sorry, i know only the lazzy way ;-)

**Comment by Nadahar** [comment]
@Sami32 I think I know where the whitespace errors come from 💡 I sometimes commit things on one of my VMs if I've tested it there. In this case, it was my XP VM where I tested that it worked as intended. I haven't configured neither Eclipse or Git to do the checks on all the VM's. There are so many installations that it would be a "lot" of work to do, and also a hazzle to remember when I configure a new one. Usually I look over and verify stuff I've done on one of the VMs before the commit is "final", but since this was such a small commit I didn't do it.

Not sure how to deal with that actually, I'm not rebasing master for it. After all, I guess it's not the end of the world, although annoying because it can complicate future diffs and conflict resolution.

**Pull request merged**
