### PR TITLE
Fix OGA in web renderer

### LINKED ISSUE #62: OGG files without video stream are considered as video
The OGG files without video stream have to be considered as OGA in the web renderer.
Because as it is now they fail to play.

### PR DESCRIPTION
**Pull request by Sami32**
Need a Java expert to fix the OGG files without video stream to be considered as OGA in the web renderer.

😉

This should now fix #62

---
This change is [Reviewable](https://reviewable.io/reviews/digitalmediaserver/digitalmediaserver/60)

### CODE REVIEW

**Comment by Nadahar** [comment]
Damn, where should we find one of those?

**Comment by Nadahar** [comment]
This doesn't seem to be a small fix, since the web interface completely ignores the normal parsing and is only based on file extensions. If must somehow be refactored so that it uses the normal parsing, where you have access to the `DLNAMediaInfo` instance where this has already been resolved.

**Comment by Sami32** [comment]
Ok, so as it doesn't need to be added in this PR i will post a specific issue for that.

**Comment by Sami32** [comment]
Thank you for having looked at it 👍

**Comment by Nadahar** [comment]
@Sami32 What will this PR do without it? Only work for files with an `OGA` extension?

**Comment by Sami32** [comment]
Yes

**Comment by Sami32** [comment]
Yes, but it is all i can fix by myself by now.

**Comment by Nadahar** [comment]
This should also fix #62

**Comment by Nadahar** [comment]
The "requested changes" are simply testing.

**Comment by Sami32** [comment]
Hehe, work great 👍 

I knew that we have a Java expert around 😉

**Pull request merged**
