### PR TITLE
Update sevenzip library

### PR DESCRIPTION
**Pull request by Sami32**
Taken from [here](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/987/commits/9d0e876418edbd0138411e20a583dbb8fd2a901c).

Perhaps [this commit](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/987/commits/c83fe283f366efbd250cb5600e72c8ca287caa7c) should also be added?

---
This change is [Reviewable](https://reviewable.io/reviews/digitalmediaserver/digitalmediaserver/36)

### CODE REVIEW

**Comment by Nadahar** [comment]
There are changes here that isn't related to the updated library and *will* break stuff. Either the original commit wasn't "clean" (only did what it announced) or your cherry-picking has had unintended effects.

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/net/pms/dlna/SevenZipEntry.java, line 54 at r1](https://beta.reviewable.io/reviews/digitalmediaserver/digitalmediaserver/36#-LASre7A0-glu2dAOJgj:-LASre7A0-glu2dAOJgk:b-m2jge2) ([raw file](https://github.com/digitalmediaserver/digitalmediaserver/blob/2bb8fd03fe050bb99ea1f093b89ce21a60f36ce8/src/main/java/net/pms/dlna/SevenZipEntry.java#L54)):*
> ```Java
> 
> 		return super.getThumbnailURL(profile);
> 	}
> ```

This and a lot of other changes are unrelated and wrong.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/digitalmediaserver/digitalmediaserver/36#-:-LASqshf7wRYayhfFZuK:b4qw1us)*

**Comment by Nadahar** [comment]
I started to try to merge the referenced implementation, but it lead to so many issues that I just left it for later in branch [SevenZipAtamariyaImpl](https://github.com/DigitalMediaServer/DigitalMediaServer/tree/SevenZipAtamariyaImpl).

I've now updated this branch to only use the new library. Most of the bugs that were already there are still in place, but at least we get rid of the "manual" dependency.

**Comment by Nadahar** [comment]
@Sami32 Are we waiting for something in particular?

**Comment by Sami32** [comment]
No but i'm missed time.
Any reason to hurry?

**Comment by Nadahar** [comment]
@Sami32 I just want do get these small things "out of the way" before I forget about them :wink: I'm not quite sure what you want to test that is relevant to this PR, testing 7-zip archives in general will reveal more bugs than features - so I guess I'm afraid you'll get hung up on those. In my view, this is only about replacing the dependency.

**Comment by Sami32** [comment]
Yes,  my target has always being limited to get rid of our external library. 
As missing thumbnails support or flaw was already missing it so fixes and enhancement should be done in a separate  PR with a low priority IMO.

**Comment by Nadahar** [comment]
I agree completely, which I why I left [SevenZipAtamariyaImpl](https://github.com/DigitalMediaServer/DigitalMediaServer/tree/SevenZipAtamariyaImpl) there. If could be a starting point for further work, because even though it has many problems too, it has some good changes there that should be kept.

That's why I don't quite understand what we're waiting for with the PR.

**Comment by Nadahar** [comment]
Now you're just confusing me :wink:

**Comment by Sami32** [comment]
Just give me some time 😉

**Comment by Sami32** [comment]
Hum...not sure that [it](https://github.com/DigitalMediaServer/DigitalMediaServer/blob/sevenzip/src/main/java/net/pms/dlna/ZippedEntry.java#L117) is related as i didn't compared with an other branch:
```
ERROR 2018-07-28 22:52:34.281 [Zip Extractor] Unpack error. Possibly harmless.
java.io.IOException: Le canal de communication a été fermé
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.write(Unknown Source)
	at net.pms.dlna.ZippedEntry$1.run(ZippedEntry.java:117)
	at java.lang.Thread.run(Unknown Source)
DEBUG 2018-07-28 22:52:34.281 [Zip Extractor] Caught exception
java.io.IOException: Le canal de communication est sur le point d'être fermé
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at java.io.FilterOutputStream.close(Unknown Source)
	at net.pms.dlna.ZippedEntry$1.run(ZippedEntry.java:130)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Sami32** [comment]
Hum...i don't remember having tested that before but 7Z don't work.
The files are not showed and the folder scanning get "looped".
Even a folder name having "7Z" get discarded, hidden.

[debug.log](https://github.com/DigitalMediaServer/DigitalMediaServer/files/2238782/debug.log)

**Comment by Nadahar** [comment]
Please compare it with the behavior without this branch, or we will do this forever. I can browse them when I try, but as said there are many bugs with what's inside.

**Comment by Sami32** [comment]
It is planned when i will retest your art cover branch.
I just leave a trace as reminder.

Patience ;)

**Comment by Sami32** [comment]
That said i cannot browse them as they don't even display on this branch so we get different result.

**Comment by Nadahar** [comment]
@Sami32 I wouldn't say it was very intuitive for me, but sure :wink:

**Comment by Nadahar** [comment]
@Sami32 Have you turned on "browse archives"?

**Comment by Nadahar** [comment]
@Sami32 As I said, the log above is from UMS 6.6.1...

**Comment by Sami32** [comment]
Seriously?

**Comment by Nadahar** [comment]
```powershell
DEBUG 2017-03-09 04:36:59.453 [main] Reading log_level: "TRACE" (default: "DEBUG")
DEBUG 2017-03-09 04:36:59.500 [main] Default logfile folder set to: C:\Documents and Settings\All Users\UMS
DEBUG 2017-03-09 04:36:59.984 [main] LogBack started with configuration file: C:\Program Files\Universal Media Server\logback.xml
DEBUG 2017-03-09 04:36:59.984 [main] Reading logging_filter_logs_tab: "TRACE" (default: "INFO")
DEBUG 2017-03-09 04:37:00.000 [main] Reading logging_buffered: true (default: false)
INFO  2017-03-09 04:37:00.000 [main] Buffered logging turned ON
DEBUG 2017-03-09 04:37:00.031 [main] Thu Mar 09 04:37:00 CET 2017
DEBUG 2017-03-09 04:37:00.031 [main] Reading cred.path: "C:\Documents and Settings\All Users\UMS\UMS.cred" (default: "")
DEBUG 2017-03-09 04:37:00.421 [main] Writing PID: 536
DEBUG 2017-03-09 04:37:00.421 [main] 
INFO  2017-03-09 04:37:00.421 [main] Starting Universal Media Server 6.6.1-SNAPSHOT
INFO  2017-03-09 04:37:00.437 [main] Based on PS3 Media Server by shagrath, copyright 2008-2014
INFO  2017-03-09 04:37:00.437 [main] http://www.universalmediaserver.com
INFO  2017-03-09 04:37:00.437 [main] 
INFO  2017-03-09 04:37:00.437 [main] Build: da4e3a447 (2017-03-08)
INFO  2017-03-09 04:37:00.437 [main] Java: Java HotSpot(TM) Client VM 1.8.0_60 32-bit by Oracle Corporation
INFO  2017-03-09 04:37:00.437 [main] OS: Windows XP 32-bit 5.1
INFO  2017-03-09 04:37:00.437 [main] Encoding: UTF-8
INFO  2017-03-09 04:37:00.437 [main] Memory: 742 MB
INFO  2017-03-09 04:37:00.453 [main] Language: English (United States)
```

**Comment by Sami32** [comment]
Damn...i don't know how i managed to get the wrong log...
Sorry for that inconverience :/

[debug.log](https://github.com/DigitalMediaServer/DigitalMediaServer/files/2238812/debug.log)

**Comment by Nadahar** [comment]
I can only find one 7z file, `WAVs.7z`. I can see that the folder is listed while browsing from the DIDL-Lite:
```xml
  <container childCount="5" id="1309" parentID="1113" restricted="1">
    <dc:title>WAVs.7z</dc:title>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_SM;DLNA.ORG_FLAGS=00900000000000000000000000000000">http://192.168.1.29:5252/get/1309/thumbnail0000JPEG_SM_WAVs.7z.jpg</res>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN;DLNA.ORG_FLAGS=00900000000000000000000000000000">http://192.168.1.29:5252/get/1309/thumbnail0000JPEG_TN_WAVs.7z.jpg</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://192.168.1.29:5252/get/1309/thumbnail0000JPEG_SM_WAVs.7z.jpg</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://192.168.1.29:5252/get/1309/thumbnail0000JPEG_TN_WAVs.7z.jpg</upnp:albumArtURI>
    <upnp:class>object.container.storageFolder</upnp:class>
  </container>
```

There's one other file `Audio_Thumbnails_Test.7z.zip` which won't work for obvious reasons, as it will be opened by 'ZippedFile` (and crash):
```powershell
ERROR 2018-07-29 14:37:22.468 [Library Scanner] Error reading zip file
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at net.pms.dlna.ZippedFile.<init>(ZippedFile.java:41)
	at net.pms.dlna.MapFile.manageFile(MapFile.java:233)
	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:333)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:272)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:282)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:282)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:282)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:228)
	at net.pms.dlna.DLNAMediaDatabase.run(DLNAMediaDatabase.java:952)
	at java.lang.Thread.run(Unknown Source)
```

So, I'm still wondering exactly what isn't showing...

**Comment by Sami32** [comment]
The .7z ones.
That sample that you showed was already forgotten by me, but it doesn't concern any case here as it seem a fake ZIP to avoid the Github limitation when posting issue.

But after having looked at the log i suspect that it could be a "Panasonic" display issue. Will see later.

**Comment by Sami32** [comment]
Ok, now it work and i can see enhancement as half of the thumbnails are now displayed when they wasn't before.

I don't know what happened before but resetting the database solved my issue. That said i also did a Git hard reset it in case you had rebased this branch.

**Pull request merged**
