### PR TITLE
FPS implementation in renderer's configuration

### PR DESCRIPTION
**Pull request by Sami32**
To be able to fine tune the renderer's configuration supported lines.

Note: I still have to work on PR backport, as i get history issue. So that's my first test.

---
This change is [Reviewable](https://reviewable.io/reviews/digitalmediaserver/digitalmediaserver/4)

### CODE REVIEW

**Comment by Sami32** [comment]
It doesn't have to be merged, i just test the backport.
And also make it visible to everyone :wink:

**Comment by Nadahar** [comment]
@Sami32 The reason you're getting "history" issues is most likely because I've been rebasing master. I'm not going to keep doing that, but since it's early days and I keep finding things that's gone wrong during all my rebasing/merging and splitting of existing code when updating master with the last year of UMS updates, I've been rebasing it instead of adding commits.

To "fix" your fork, check it out - do a ```reset --hard origin/master``` (provided that you have fetched/your remote is up-to-date) and then force push master.

When it comes to individual PR's it might not be so easy, as some conflict resolution could be needed. If my rebasing has made trouble in some of your branches, just tell me and I can fix them.

**Comment by Sami32** [comment]
I suspected that was from your rebasing, as i have already that issue before and fixed it. I just saw taht when i checked at my PR and saw it, i guessed that come when you'he cleaned my precedent PR merge.
So, i take the easy way and create the branch on your fork. Better than keeping mad with all these conflicts :P

**Comment by Nadahar** [comment]
@Sami32 It won't be any easier if I rebase master after you've created the branch. I'm planning one more rebase of master, but just let me know when there are problems and I can fix them without much trouble.

**Comment by Sami32** [comment]
I don't want bother you with that.
That's said, you can reapprove [this PR](https://github.com/DigitalMediaServer/DigitalMediaServer/pull/3) as it'll avoid me to rebase each time.

**Comment by Nadahar** [comment]
@Sami32 I suddenly realized that I lied to you regarding how to fix your fork. I was thinking wrong, "origin" in that case is your fork, not the DMS repo.

What you need to do is to add a new remote ```upstream``` (for example) with the address of DMS' git repo. Then fetch ```upstream``` and ```reset --hard upstream/master``` instead. Then push to origin/your fork.

**Comment by Sami32** [comment]
Never mind. I didn't followed your step ;-)
I fetch upstream and reset hard to the latest commit, but it didn't worked today when i did it.
Thanks, i'll try for the other PR later.

**Comment by Nadahar** [comment]
@Sami32 The reset hard procedure is only to make your master branch "in sync". I'm sure you understand that you can't do that on a branch with content you actually want to keep, as a hard reset will change the branch's head pointer to a completely different commit, making it lose all reference to what's currently there. 

"Fixing" branches is easy though, here's what I do: I figure out which is the last commit that doesn't "belong to the PR" (that was previously in master). I make a new branch which points to the corresponding commit from the "new" master. I then cherry pick all the remaining commits from the PR into the new branch.

Given that there are no conflicts, this will usually mean that the new branch has the same content as the original PR, but based on the "current" master branch. You could also just rebase the old PR direcly on top of the new master, but that will probably create a lot of conflicts that you avoid by doing it the way I described it. Rebasing is actually just a set of scripts that automate cherry-picking anyway, so why not do cherry-pick just the commits we want?

**Comment by Sami32** [comment]
Yes, it what i do when i cherry-pick into a new branch into your fork.

You guessed right :wink: rebasing make me too much conflict and that the easy i found to avoid that.
You began to know me :rofl:

**Comment by Nadahar** [comment]
@Sami32 Nobody likes conflicts if they can be avoided, I do the same. But, sometimes there are actual conflicts that will still arise when you use cherry-pick.

**Comment by Sami32** [comment]
Lets hope that will be only with big PRs :wink:

**Pull request closed without merging**
