### PR TITLE
PS4 enhancement attempt

### PR DESCRIPTION
**Pull request by Sami32**
These renderers was done in an unmerged PR more than one year ago and have not been tested yet.

---
This change is [Reviewable](https://reviewable.io/reviews/digitalmediaserver/digitalmediaserver/114)

### CODE REVIEW

**Comment by Sami32** [comment]
@MadokaAyukawa  Feel free to test and report back ;-)

In case you have the PS4 Pro i also have this renderer configuration somewhere.

**Comment by MadokaAyukawa** [comment]
I started testing this file, but I only have a lame-ass OG PS4. Sorry. :)

I ran across this file that the PS4 wants to stream (and the PS3 wants to transcode correctly), but I get audio but no video and then the PS4 will stop trying to play it after a few seconds.

```
[TRACE 2018-10-26 10:33:53.912 [HTTPv2 Request Worker 9] MediaInfo parsing results for "[T-N]Densha_Otoko_01[5740B853].avi":
  Format: "AVI"                 Duration: 0:59:19.489         Overall Bitrate: 1284483      Cover: No
  FPS: 29.970
  - Video track ID: 0
    Format: "MPEG-4 Visual"       Profile: "Advanced Simple@L5" CodecID: "XVID"               Duration: 0:59:19.489
    Bitrate: 1144669              Width: 704                    Height: 396                   Colorimetry: 4:2:0
    Chroma: 4:2:0                 PAR: 1.000                    DAR: 16:9                     Scan Type: Progressive
    FPS: 29.970                   QPel: "No"                    GMC: "3"                      Bit Depth: 8
    Delay: 0
  - Audio track ID: 1
    Format: "MPEG Audio"          Version: "Version 1"          Profile: "Layer 3"            CodecID: "55"
    Duration: 0:59:19.431         BitRate Mode: CBR             Bitrate: 128000               Channel(s): 2
    Samplerate: 48000             Delay: 0                      Delay Source: Stream
TRACE 2018-10-26 10:33:53.912 [HTTPv2 Request Worker 9] Parsing results for file "[T-N]Densha_Otoko_01[5740B853].avi": Container: AVI, Size: 571512832, Video Bitrate: 1284483, Video Tracks: 1, Video Codec: mpeg4asp, Duration: 0:59:19.489, Video Resolution: 704 x 396, Display Aspect Ratio: 16:9, Scan Type: Progressive, Framerate: 29.970, Audio Tracks: 1 [Audio Codec: MP3, Bitrate: 128000, Bitrate Mode: CONSTANT, Channels: 2, Sample Frequency: 48000 Hz, Delay: 0 ms], Mime Type: video/avi
TRACE 2018-10-26 10:33:53.912 [HTTPv2 Request Worker 9] Adding new child "[T-N]Densha_Otoko_01[5740B853].avi" with class "RealFile"
TRACE 2018-10-26 10:33:53.912 [HTTPv2 Request Worker 9] This video does not have subtitles
TRACE 2018-10-26 10:33:53.912 [HTTPv2 Request Worker 9] Getting player for resource "[T-N]Densha_Otoko_01[5740B853].avi"
TRACE 2018-10-26 10:33:53.912 [HTTPv2 Request Worker 9] Returning compatible player "FFmpeg Video"
TRACE 2018-10-26 10:33:53.912 [HTTPv2 Request Worker 9] Matched support line f:avi      v:mpeg4asp|mpeg4sp|h264   a:aac-lc|ac3|mp3                   m:video/avi
TRACE 2018-10-26 10:33:53.912 [HTTPv2 Request Worker 9] Final verdict: "[T-N]Densha_Otoko_01[5740B853].avi" will be streamed]
```
But the PS4 will stream the following file.
```
MediaInfo parsing results for "[T-N]Trick1_04[D1A1E260].avi":
  Format: "AVI"                 Duration: 0:45:26.057         Overall Bitrate: 1085093      Cover: No
  FPS: 29.970
  - Video track ID: 0
    Format: "MPEG-4 Visual"       Profile: "Advanced Simple@L5" CodecID: "XVID"               Duration: 0:45:26.057
    Bitrate: 881204               Width: 640                    Height: 480                   Colorimetry: 4:2:0
    Chroma: 4:2:0                 PAR: 1.000                    DAR: 4:3                      Scan Type: Progressive
    FPS: 29.970                   QPel: "No"                    GMC: "0"                      Bit Depth: 8
    Delay: 0
  - Audio track ID: 1
    Format: "MPEG Audio"          Version: "Version 1"          Profile: "Layer 3"            CodecID: "55"
    Duration: 0:45:26.020         BitRate Mode: CBR             Bitrate: 192000               Channel(s): 2
    Samplerate: 48000             Delay: 0                      Delay Source: Stream
TRACE 2018-10-26 10:30:59.873 [HTTPv2 Request Worker 1] Parsing results for file "[T-N]Trick1_04[D1A1E260].avi": Container: AVI, Size: 369753024, Video Bitrate: 1085093, Video Tracks: 1, Video Codec: mpeg4asp, Duration: 0:45:26.057, Video Resolution: 640 x 480, Display Aspect Ratio: 4:3, Scan Type: Progressive, Framerate: 29.970, Audio Tracks: 1 [Audio Codec: MP3, Bitrate: 192000, Bitrate Mode: CONSTANT, Channels: 2, Sample Frequency: 48000 Hz, Delay: 0 ms], Mime Type: video/avi
TRACE 2018-10-26 10:30:59.873 [HTTPv2 Request Worker 1] Adding new child "[T-N]Trick1_04[D1A1E260].avi" with class "RealFile"
TRACE 2018-10-26 10:30:59.873 [HTTPv2 Request Worker 1] This video does not have subtitles
TRACE 2018-10-26 10:30:59.873 [HTTPv2 Request Worker 1] Getting player for resource "[T-N]Trick1_04[D1A1E260].avi"
TRACE 2018-10-26 10:30:59.873 [HTTPv2 Request Worker 1] Returning compatible player "FFmpeg Video"
TRACE 2018-10-26 10:30:59.873 [HTTPv2 Request Worker 1] Matched support line f:avi      v:mpeg4asp|mpeg4sp|h264   a:aac-lc|ac3|mp3                   m:video/avi
TRACE 2018-10-26 10:30:59.873 [HTTPv2 Request Worker 1] Final verdict: "[T-N]Trick1_04[D1A1E260].avi" will be streamed
```

**Comment by Sami32** [comment]
Oops...correct. I've omit a parameter. It should be corrected now.
It is why testing is so important ;-)
Thank you very much for your feedback +1

**Comment by MadokaAyukawa** [comment]
I apologize that I am not savvy enough to figure out what's wrong when things don't work. I looked at your change, and it was a simple one and evident from the video data I posted in retrospect.

I can confirm that with that change the Densha Otoko file is now transcoded and playable.

One note on PS4 subtitle support. It doesn't "really" support .ass subtitles. It will display them as plain text subs, but all font/formatting is not honored at all. As such, the viewer is not getting the experience that the subtitler intended at all. I will always transcode my .ass subs over on the PS4.

**Comment by MadokaAyukawa** [comment]
I removed ASS from that line in the config in the past, as I want the subs to look as intended. Many times there will be translations for signs that are placed specially on screen or different colored text per speaker. But that's just personal preference.

**Comment by Nadahar** [comment]
@MadokaAyukawa When it comes to the ASS subtitles this is tricky territory. Some users probably won't care about coloration or special placement and just want to avoid transcoding. I think this is a typical case where a manual pick in the TRANSCODE folder is the best option.

When it comes to what DMS considers "problematic subtitles" I'm afraid that comes directly from UMS, and I don't even know the criteria myself. There are so many things to fix, and that one is definitely one that needs looking into in the future. FFmpeg might have evolved into supporting things it didn't when this was defined as well.

**Comment by Nadahar** [comment]
The subtitles build of DMS should have resolved several issues related to picking the correct subtitles stream though, so I'd just try to turn it off. You can always pick MEncoder manually in the TRANSCODER folder.

**Comment by Sami32** [comment]
It defer to MEncoder all the embedded  text kind subtitles except the ASS ones, more the VOBSUB image subtitles.
That is because of the old FFmpeg version used.

I've only made testing build for macOS by now to avoid that.

**Comment by SubJunk** [comment]
I periodically test newer versions of FFmpeg and haven't noticed any fixes for it. They have an open issue for it but no one is interested enough to fix it - it is just not enough of a problem for enough people.

The reason FFmpeg can't handle those files in time is that it needs to extract the subtitles from the file before it can write them, which causes timeouts for us while we wait for that extraction. MEncoder is able to write the subtitles without the extraction step.

**Comment by Sami32** [comment]
@ma Please, could do a new test with these new changes and report back? Thanks ;-)
https://raw.githubusercontent.com/DigitalMediaServer/DigitalMediaServer/cc4610848d6e38a96ae5ba8fcfa9436d3c2998cf/src/main/external-resources/renderers/Sony-PlayStation4.conf

Note: Just replace `H264LevelLimit = 4.2` by `H264Level41Limit = true` for the time being.

**Comment by MadokaAyukawa** [comment]
Should this be the PS4 or PS3 config file? As the discussion about that 4.2 file was about the PS3. I am happy to test both renderers.

**Comment by Nadahar** [comment]
@MadokaAyukawa The level support #115 isn't finished yet, so that won't work for now.

**Comment by Sami32** [comment]
@MadokaAyukawa The 4.2 video level is a specification limitation used for the two PlayStation renderers.
These renderers can work with your DMS build but also depends on 2 others unmerged PRs.
It is why i asked you to replace and do some various streaming tests ;-)

**Comment by MadokaAyukawa** [comment]
Thanks for the explanations. I'll report back after testing.

**Comment by Sami32** [comment]
@MadokaAyukawa Can be merged as soon as you will confirme that nothing wrong happened with this PS4 renderer configuration file.

**Comment by MadokaAyukawa** [comment]
Nothing that I've noticed so far. With the new build, it streamed the L4,2 file over ok.

**Comment by Sami32** [comment]
@MadokaAyukawa Thank you very much for your feedback :+1:

**Comment by Sami32** [comment]
@MadokaAyukawa
>There are some files I know FFmpeg has trouble with such as video files with multiple audio and subtitle streams. I can't even use the transcode folder to pick the combination for FFmpeg; I will need to use MEncoder for those.

Could you pooint me the a such media?
I never met myself and suspect that it only come from the code and have nothing to do with FFmpeg.

**Comment by MadokaAyukawa** [comment]
IIRC, this is one such file. You only need to get one episode.

https://nyaa.si/view/1062197

**Comment by Sami32** [comment]
Thank you +1
I see at least 2 ways of solve that for FFmpeg, it worked for me, and perhaps a third one but i will need a big sized media with embedded ASS subtitle to test it.

**Comment by MadokaAyukawa** [comment]
This is a movie and large.

https://nyaa.si/view/1081758

**Comment by MadokaAyukawa** [comment]
My bad. It only has .srt. Try this one.

https://nyaa.si/view/1068655

**Comment by Sami32** [comment]
Perfect, thank you :smiley:

**Pull request merged**
